#import "lib/setup.typ": setup
#show: setup

#[
  #set heading(outlined: false, numbering: none)
  = Preface
]
Before you lies the thesis "Investigating Google Cloud Hyperdisks for Uber's Cloud Development Environment.", submitted in fulfillment of the requirements for the Bachelor of Science in Software Engineering at the Amsterdam University of Applied Sciences. I was engaged in researching this topic as a Software Engineer at Uber, from February of 2025 until August of 2025.

This thesis has felt pivotal to my career, feeling like the end of my formative years in software. I started this Bachelors degree in 2018, nearly 7 years ago. I was only 16 at the time, and I had no idea what I wanted to do - I knew I had a passion for programming and building things, but I didn't know what interests me specifically. After my first year, I paused my studies due to the COVID-19 pandemic, continuing programming in my personal time. Eventually, I returned to my studies in 2022, enrolling in the transfer minor for the Master's curriculum at VU Amsterdam. This minor lead me to realise I was incredibly passionate about low-level systems programming, theoretical computer science, and research. At times, I felt like starting at an applied sciences university had been a mistake, and a research university would have been a better fit.

Regardless, I finished my minor and went back to the AUAS. The next part of my curriculum was my first internship, which I chose to do at Uber in February of 2024. This internship proved to me that despite studying in applied sciences, I can find myself working on novel problems: I investigated GPU acceleration for cloud-based Android emulators using QEMU. After this first internship, I was asked to join Uber full-time. Since joining full-time in September, I have had opportunities to work on truly interesting problems: problems that remind me of my minor at VU Amsterdam, including this thesis, which has proven to me that I have found my true passion.

Lastly, I would like to acknowledge the people that have supported me throughout this journey. I would like to thank my thesis supervisor, Dr. Ian Bradford, for his guidance and support: having a supervisor with a strong background in research and academia has proven to be invaluable for me to write this thesis, and his feedback on my technical writing has fundamentally improved my technical writing competency. I would like to thank my company supervisor, Matas, for his guidance and mentorship. Finding the overlap between writing theoretical research and being productive for the business has been challenging, but Matas proved to be a great mentor: consistently empowering me to lead, make my own decisions, and carve out my own work. Finally, I would like to thank my friend and coworker Ana, who has provided immeasurable emotional support throughout this thesis: the academic struggle is finally coming to an end, and I've truly appreciated having someone to relate to.