// == Relevance to disk performance
// As previously mentioned, Uber has adopted the concept of monorepos for the vast majority of their codebases, and these monorepos are used by engineers using cloud development environments. Within the usage of monorepos, there are a number of scenarios where disk performance is assumed to be relevant. These assumptions are investigated in-depth in the core of this research, but they are introduced in this section to provide context.

// There are a number of scenarios related to building and executing projects. In monorepos, projects have direct source code dependencies on other projects and libraries in the same monorepo. When a new instance of the monorepo is cloned and a given project is built, the source code for all dependencies must first be compiled - this is known as a _cold build_. For large projects with many transient dependencies, a cold build could require millions of source code lines being read from the disk in order to be compiled. The more performant the disk is, the faster the source code can be read. However, subsequent builds may also depend on disk performance: when dependencies are cached, they still need to be read from the disk to create an executable build of the project. Therefore, the faster the cache can be read from the disk, the faster the project can be compiled.

// Outside of building and executing projects, disk performance plays a role in other operations as well. One such example is the `git status` command, which returns modified files across the monorepo, and is frequently used during the software development lifecycle. The implementation of this command recursively traverses all directories in the monorepo, requiring a significant amount of disk operations. Another example is project-wide code search: most IDE's provide a feature where directories can be scanned for text occurrences in files, where the IDE needs to read the contents of all source files in a given project. Traversing the directories recursively and reading the contents of the source code files are operations that rely on disk performance.

// The definition of _primary workloads_ is as follows: as previously mentioned, the  These environments allow engineers to perform many different tasks, as any software engineer does. By _primary workloads_, we specifically investigate the most commonly performed tasks by engineers, focusing on their core workflow. 

// Specifically, the primary workloads selected for investigation are build performance, IDE operations and git latency. Each of these workloads are individually investigated in this chapter, yielding data that is statistically analyzed. At the end of the chapter, the analysis is used to draw conclusions, combined with the context of the goal.
